name: ci

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set IMAGE (lowercase)
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          echo "IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t "$IMAGE:dev" .

      - name: Push image
        run: docker push "$IMAGE:dev"

      - name: Output image ref
        run: echo "Image: $IMAGE:dev"
